In [65]:
import json

with open("../data/stock_data.json", "r") as f:
    data = json.load(f)

data

{'c': 427.1,
 'd': 1.89,
 'dp': 0.4445,
 'h': 436.35,
 'l': 420.03,
 'o': 425.71,
 'pc': 425.21,
 't': 1770839585}

In [66]:
import pandas as pd

df = pd.json_normalize(data)
df

       c     d      dp       h       l       o      pc           t
0  427.1  1.89  0.4445  436.35  420.03  425.71  425.21  1770839585

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c       1 non-null      float64
 1   d       1 non-null      float64
 2   dp      1 non-null      float64
 3   h       1 non-null      float64
 4   l       1 non-null      float64
 5   o       1 non-null      float64
 6   pc      1 non-null      float64
 7   t       1 non-null      int64
dtypes: float64(7), int64(1)
memory usage: 196.0 bytes

In [ ]:
df[["c", "t"]]

       c           t
0  427.1  1770839585

In [49]:
df.rename(columns={
    "c": "current_price",
    "d": "difference",
    "dp": "percent_different",
    "h": "high_price_day",
    "l": "low_price_day",
    "o": "open_price_day",
    "pc": "previous_close_price",
    "t": "timestamp"
}, inplace=True)

df

,current_price,difference,percent_different,high_price_day,low_price_day,open_price_day,previous_close_price,timestamp
0,426.18,0.97,0.2281,436.35,420.03,425.71,425.21,1770837493

In [50]:
df.timestamp = pd.to_datetime(df.timestamp, unit="s", utc=True).dt.tz_convert("Europe/Lisbon")
df

,current_price,difference,percent_different,high_price_day,low_price_day,open_price_day,previous_close_price,timestamp
0,426.18,0.97,0.2281,436.35,420.03,425.71,425.21,2026-02-11 19:18:13+00:00